services:
  pinocchio-example:
    build: .
    container_name: pinocchio_container
    network_mode: host  # Use host network to allow X11 forwarding
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw  # x11 mapping
      - .:/workspace                       
    privileged: true                      
    stdin_open: true
    tty: true
